version: "3.5"

services:
  mongodb:
    image: mongo:4.2.9

  postapp:
    build: .
    command: ruby /app/app.rb
    volumes:
      - ./app:/app
    ports:
      - "4567:4567"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGODB_NAME=development
