version: "3.5"

services:
  mongo:
    image: mongo:4.2.9
    env_file: .env.development
    networks:
      - app
    volumes:
      - db:/data/db

  postapp:
    build: .
    env_file: .env.development
    networks:
      - app
    command: /app/boot.sh
    volumes:
      - ./app:/app
    ports:
      - "4567:4567"
    depends_on:
      - mongo
    links:
      - mongo

networks:
  app:

volumes:
  db:
