development:
  clients:
    default:
      database: '<%= ENV["MONGO_DB"] %>'
      hosts:
        - '<%= ENV["MONGO_HOST"] %>:27017'
      options:
        server_selection_timeout: 5
    secondary:
      database: '<%= ENV["MONGO_DB"] %>'
      hosts:
        - '<%= ENV["MONGO_HOST"] %>:27017'
      options:
        server_selection_timeout: 5
